name: univagenda
description: Application pour voir son agenda universitaire à tout moment et facilement.
version: 5.0.0+20231006
publish_to: "none"

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: 3.19.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  after_layout: 1.2.0
  collection: 1.18.0
  firebase_analytics: 10.8.8
  firebase_core: 2.26.0
  firebase_crashlytics: 3.4.17
  flutter_markdown: 0.6.21
  flutter_material_color_picker: 1.2.0
  flutter_timezone: 1.0.8
  html: 0.15.4
  http: 1.2.0
  icalendar_parser: 2.0.0
  image_picker: 1.0.7
  intl: 0.18.1
  introduction_screen: 3.1.12
  mobile_scanner: 4.0.1
  package_info_plus: 5.0.1
  path_provider: 2.1.2
  permission_handler: 11.3.0
  provider: 6.1.2
  shared_preferences: 2.2.2
  syncfusion_flutter_calendar: 24.2.9
  syncfusion_localizations: 24.2.9
  timezone: 0.9.2
  url_launcher: 6.2.5
  uuid: 4.3.3
  material_color_utilities: 0.8.0

dev_dependencies:
  dependency_validator: 3.2.3
  flutter_launcher_icons: 0.13.1
  flutter_lints: 3.0.1

flutter:
  uses-material-design: true

  assets:
    - res/images/
    - res/locales/

  fonts:
    - family: GoogleSans
      fonts:
        - asset: res/fonts/GoogleSans-Regular.ttf
          style: normal
          weight: 500

        - asset: res/fonts/GoogleSans-Medium.ttf
          style: normal
          weight: 600

        - asset: res/fonts/GoogleSans-Bold.ttf
          style: normal
          weight: 700

flutter_launcher_icons:
  android: true
  ios: true
  image_path_android: "res/images/icon_circle.png"
  image_path_ios: "res/images/icon_ios.png"
  adaptive_icon_background: "#FFFF0000"
  adaptive_icon_foreground: "res/images/icon_foreground.png"
