name: univagenda
description: Application pour voir son agenda universitaire à tout moment et facilement.
version: 4.4.0+20200908
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  after_layout: 1.1.0
  device_calendar: 4.0.1-dev.13167
  firebase_analytics: 8.3.1
  firebase_core: 1.6.0
  firebase_crashlytics: 2.2.1
  syncfusion_flutter_calendar: 19.2.59
  flutter_markdown: 0.6.6
  flutter_material_color_picker: 1.1.0+2
  flutter_native_timezone: 1.1.0
  html: 0.15.0
  http: 0.13.3
  introduction_screen: 2.1.0
  package_info: 2.0.2
  path_provider: 2.0.3
  provider: 6.0.0
  # qrcode:
  #   git: 
  #     url: git@github.com:Pyozer/qrcode
  #     path: qrcode
  shared_preferences: 2.0.1
  timezone: 0.7.0
  url_launcher: 6.0.10
  uuid: 3.0.4

dev_dependencies:
  flutter_launcher_icons: 0.9.2

flutter:
  uses-material-design: true

  assets:
    - res/images/
    - res/locales/

  fonts:
     - family: GoogleSans
       fonts:
          - asset: res/fonts/GoogleSans-Regular.ttf
            style: normal
            weight: 500

          - asset: res/fonts/GoogleSans-Medium.ttf
            style: normal
            weight: 600

          - asset: res/fonts/GoogleSans-Bold.ttf
            style: normal
            weight: 700

flutter_icons:
  android: true
  ios: true
  image_path_android: "res/images/icon_circle.png"
  image_path_ios: "res/images/icon_ios.png"
  adaptive_icon_background: "#FFFF0000"
  adaptive_icon_foreground: "res/images/icon_foreground.png"
