name: univagenda
description: Application pour voir son agenda universitaire à tout moment et facilement.
version: 5.0.0+20230117
publish_to: "none"

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  after_layout: 1.2.0
  collection: 1.17.2
  firebase_analytics: 10.4.5
  firebase_core: 2.15.1
  firebase_crashlytics: 3.3.5
  flutter_markdown: 0.6.17+2
  flutter_material_color_picker: 1.2.0
  flutter_timezone: 1.0.7
  html: 0.15.4
  http: 1.1.0
  icalendar_parser: 2.0.0
  image_picker: 1.0.4
  intl: 0.18.1
  introduction_screen: 3.1.11
  mobile_scanner: 3.4.1
  package_info_plus: 4.1.0
  path_provider: 2.1.1
  permission_handler: 10.4.3
  provider: 6.0.5
  shared_preferences: 2.2.1
  syncfusion_flutter_calendar: 22.2.11
  syncfusion_localizations: 22.2.11
  timezone: 0.9.2
  url_launcher: 6.1.14
  uuid: 4.0.0

dev_dependencies:
  flutter_launcher_icons: 0.13.1
  flutter_lints: 2.0.3

flutter:
  uses-material-design: true

  assets:
    - res/images/
    - res/locales/

  fonts:
    - family: GoogleSans
      fonts:
        - asset: res/fonts/GoogleSans-Regular.ttf
          style: normal
          weight: 500

        - asset: res/fonts/GoogleSans-Medium.ttf
          style: normal
          weight: 600

        - asset: res/fonts/GoogleSans-Bold.ttf
          style: normal
          weight: 700

flutter_icons:
  android: true
  ios: true
  image_path_android: "res/images/icon_circle.png"
  image_path_ios: "res/images/icon_ios.png"
  adaptive_icon_background: "#FFFF0000"
  adaptive_icon_foreground: "res/images/icon_foreground.png"
